# Generated by Django 4.0 on 2022-02-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entreprise', '0003_entreprise_anneecreation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='ConfirmMDP',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='MDP',
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='activite',
            field=models.CharField(blank=True, default='Activité', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='adresse',
            field=models.CharField(blank=True, default='Entreprise@gmail.com', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='anneeCreation',
            field=models.IntegerField(blank=True, default=2000, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='capital',
            field=models.IntegerField(blank=True, default=10000, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='chiffreAffaire',
            field=models.IntegerField(blank=True, default=10000, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='effectif',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='formeJuridique',
            field=models.CharField(blank=True, choices=[('SCS', 'SCS'), ('SNC', 'SNC'), ('SARL', 'SARL'), ('SA', 'SA'), ('SAS', 'SAS'), ('GIE', 'GIE'), ('SEP', 'SEP'), ('SCP', 'SCP'), ('SCI', 'SCI'), ('SP', 'SP')], default='SP', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='nomDirecteur',
            field=models.CharField(blank=True, default='Directeur', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='nomEntreprise',
            field=models.CharField(blank=True, default='Entreprise', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='numeroContribuable',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
