# Generated by Django 4.0 on 2022-02-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employé',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEmploye', models.CharField(max_length=50, null=True)),
                ('prenomEmploye', models.CharField(max_length=50, null=True)),
                ('dateNaissance', models.DateField(null=True)),
                ('lieuNaissance', models.CharField(max_length=50, null=True)),
                ('nationalite', models.CharField(choices=[('Allemande', 'Allemande'), ('Algérien', 'Algérien'), ('Angolais', 'Angolais'), ('Argentin', 'Argentin'), ('Américaine', 'Américaine'), ('Anglaise', 'Anglaise'), ('Australien', 'Australien'), ('Autrichien', 'Autrichien'), ('Bahamien', 'Bahamien'), ('Belge', 'Belge'), ('Béninois', 'Béninois'), ('Bisseau-Guinéen', 'Bisseau-Guinéen'), ('Brésilien', 'Brésilien'), ('Burkinabé', 'Burkinabé'), ('Burundi', 'Burundi'), ('Camerounaise', 'Camerounaise'), ('Canadienne', 'Canadienne'), ('cap-verdien', 'cap-verdien'), ('Chilien', 'Chilien'), ('Chinois', 'Chinois'), ('Colombien', 'Colombien'), ('Congolais', 'Congolais'), ('Corée du sud', 'Corée du sud'), ('Coréen', 'Coréen'), ('Cubain', 'Cubain'), ('Danois', 'Danois'), ('Egyptien', 'Egyptien'), ('Equatorien', 'Equatorien'), ('Espagnole', 'Espagnole'), ('Estonien', 'Estonien'), ('Etyiopien', 'Etyiopien'), ('Finlandais', 'Finlandais'), ('Française', 'Française'), ('Gabonais', 'Gabonais'), ('gambien', 'gambien'), ('ghanéen', 'ghanéen'), ('Grec', 'Grec'), ('Guinéenne', 'Guinéenne'), ('Haïtien', 'Haïtien'), ('Hongrois', 'Hongrois'), ('Indien', 'Indien'), ('Indonésien', 'Indonésien'), ('Irlandais', 'Irlandais'), ('Islandais', 'Islandais'), ('Israélien', 'Israélien'), ('Italien', 'Italien'), ('Ivoirien', 'Ivoirien'), ('Jamaïquain', 'Jamaïquain'), ('Japonais', 'Japonais'), ('Jordanien', 'Jordanien'), ('Kényen', 'Kényen'), ('Libye', 'Libye'), ('Marocain', 'Marocain'), ('Mexicain', 'Mexicain'), ('Motswanan', 'Motswanan'), ('Mozambique', 'Mozambique'), ('Namibie', 'Namibie'), ('Nigeria', 'Nigeria'), ('Nigérien', 'Nigérien'), ('Norvégien', 'Norvégien'), ('Pakistanais', 'Pakistanais'), ('Palestinien', 'Palestinien'), ('Péruvien', 'Péruvien'), ('Philippin', 'Philippin'), ('Polonais', 'Polonais'), ('Portugais', 'Portugais'), ('Québécois', 'Québécois'), ('Roumain', 'Roumain'), ('Russe', 'Russe'), ('Sénégalais', 'Sénégalais'), ('Suédois', 'Suédois'), ('Tchadien', 'Tchadien'), ('Tchèque', 'Tchèque'), ('Tunisienne', 'Tunisienne'), ('Vietnamienne', 'Vietnamienne'), ('Zambien', 'Zambien'), ('Zimbabwéen', 'Zimbabwéen')], max_length=50, null=True)),
                ('statusMatrimonial', models.CharField(choices=[('Marié(e)', 'Marié(e)'), ('Célibataire', 'Célibataire'), ('Divorsé(e)', 'Divorsé(e)')], max_length=50, null=True)),
                ('fonction', models.CharField(max_length=50, null=True)),
                ('typeContrat', models.CharField(choices=[('Durée déterminée', 'Durée déterminée'), ('Durée indéterminée', 'Durée indéterminée')], max_length=50, null=True)),
                ('dateRecrutement', models.DateField(null=True)),
                ('dateFin', models.DateField(null=True)),
                ('salaireBase', models.IntegerField(null=True)),
                ('salaireNet', models.IntegerField(null=True)),
            ],
        ),
    ]
