# Generated by Django 4.0 on 2022-02-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEntreprise', models.CharField(max_length=50, null=True)),
                ('adresse', models.CharField(max_length=50, null=True)),
                ('MDP', models.CharField(max_length=100, null=True)),
                ('ConfirmMDP', models.CharField(max_length=100, null=True)),
                ('anneeCreation', models.IntegerField(default='2002-11-13', null=True)),
                ('activite', models.CharField(max_length=100, null=True)),
                ('effectif', models.IntegerField(null=True)),
                ('capital', models.IntegerField(null=True)),
                ('nomDirecteur', models.CharField(max_length=50, null=True)),
                ('numeroContribuable', models.IntegerField(null=True)),
                ('formeJuridique', models.CharField(choices=[('SCS', 'SCS'), ('SNC', 'SNC'), ('SARL', 'SARL'), ('SA', 'SA'), ('SAS', 'SAS'), ('GIE', 'GIE'), ('SEP', 'SEP'), ('SCP', 'SCP'), ('SCI', 'SCI'), ('SP', 'SP')], max_length=50, null=True)),
                ('chiffreAffaire', models.IntegerField(null=True)),
            ],
        ),
    ]
