# Generated by Django 4.0 on 2022-02-08 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employé', '0003_remove_employé_salaire'),
        ('Salaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaire',
            name='Employé',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Employé.employé'),
        ),
    ]
