# Generated by Django 4.0 on 2022-02-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salaire', '0002_salaire_employé'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaire',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
