# Generated by Django 4.0 on 2022-02-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salaire', '0003_salaire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaire',
            name='salaireNet1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='salaire',
            name='totalRetenus',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='aCompte',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='crtv',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='salaireNet',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='tc',
            field=models.FloatField(null=True),
        ),
    ]
