# Generated by Django 4.0 on 2022-02-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salaire', '0004_salaire_salairenet1_salaire_totalretenus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaire',
            name='aCompte',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
