# Generated by Django 4.0 on 2022-02-07 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employé', '0002_employé_salaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employé',
            name='Salaire',
        ),
    ]
